name: Skywars
main: com.walrusone.skywarsreloaded.SkyWarsReloaded
version: 3.0

commands:
   skywars:
      description: This is the main plugin command.
      aliases: [sw]
      usage: /<command> [args]
permissions:
  sw.*:
    description: Gives access to all sw commands
    children:
      sw.admin: true
      sw.maps: true
      sw.kits: true
      sw.player: true
      sw.allowcommands: true
  sw.admin:
    description: Gives access to the sw setspawn, list, games, endgame, and reload commands
    default: op
    children:
      sw.maps: true
      sw.kits: true
      sw.player: true
      sw.setspawn: true
      sw.reload: true
      sw.setstat: true
      sw.clearstats: true
      sw.chestadd: true
      sw.start: true
      sw.allowcommands: true
  sw.maps: 
    description: Allows a player to use all map commands.
    default: op
    children:
      sw.create: true
      sw.edit: true
      sw.listmaps: true
      sw.save: true
      sw.register: true
      sw.unregister: true
      sw.refreshmaps: true
  sw.kits:
    description: Allows a player to use all kit commands.
    default: op
    children:
      sw.kitcreate: true
      sw.kitenable: true
      sw.kitfall: true
      sw.kiticon: true
      sw.kitlockicon: true
      sw.kitperm: true
      sw.kitload: true
      sw.kitlist: true
      sw.kitlore: true
      sw.kitname: true
      sw.kitpos: true
      sw.kitregen: true
      sw.kitpvp: true
      sw.kitsoup: true
      sw.kitupdate: true
      sw.player: true
  sw.player:
    description: Allows a player to using all player commands.
    default: true
    children:
      sw.join: true
      sw.stats: true
      sw.top: true
      sw.quit: true 
  sw.join: 
    description: Allows a player to use sw join command.
    default: true
  sw.stats: 
    description: Allows a player to view player stats.
    default: true
  sw.top: 
    description: Allows a player to view the leaderboard.
    default: true
  sw.quit: 
    description: Allows a player to use sw quit command.
    default: true
  sw.setspawn:
    description: Allows a player to set a set the lobby spawn.
    default: op
  sw.start:
    description: Allows a player to use the start command.
    default: op
  sw.setstat:
    description: Allows a player to set a players stats.
    default: op
  sw.clearstats:
    description: Allows a player to clear a players stats.
    default: op
  sw.allowcommands:
    description: Allows a player to use commands when spectating or in sw.
    default: op
  sw.reload:
    description: Allows a player to use the reload command.
    default: op
  sw.chestadd:
    description: Allows a player to use the chestadd command.
    default: op
  sw.create:
    description: Allows a player to create a arena.
    default: op
  sw.edit: 
    description: Allows a player to edit a arena.
    default: op
  sw.listmaps: 
    description: Allows a player to list the available maps.
    default: op
  sw.save:
    description: Allows a player to save a arena.
    default: op
  sw.register:
    description: Allows a player to register a arena.
    default: op
  sw.unregister:
    description: Allows a player to unregister a arena.
    default: op
  sw.refreshmaps:
    description: Allows a player to reload the maps data file.
    default: op     
  sw.kitcreate: 
    description: Allows a player to use the kitcreate command.
    default: op
  sw.kitenable: 
    description: Allows a player to use the kitenable command.
    default: op
  sw.kitfall: 
    description: Allows a player to use the kitfall command.
    default: op
  sw.kiticon: 
    description: Allows a player to use the kiticon command.
    default: op
  sw.kitlockicon: 
    description: Allows a player to use the kitlockicon command.
    default: op
  sw.kitperm: 
    description: Allows a player to use the kitperm command.
    default: op
  sw.kitload: 
    description: Allows a player to use the kitload command.
    default: op
  sw.kitlist: 
    description: Allows a player to use the kitlist command.
    default: op
  sw.kitlore: 
    description: Allows a player to use the kitlore command.
    default: op
  sw.kitname: 
    description: Allows a player to use the kitname command.
    default: op
  sw.kitpos: 
    description: Allows a player to use the kitpos command.
    default: op
  sw.kitregen: 
    description: Allows a player to use the kitregen command.
    default: op
  sw.kitpvp: 
    description: Allows a player to use the kitpvp command.
    default: op
  sw.kitsoup: 
    description: Allows a player to use the kitsoup command.
    default: op
  sw.kitupdate: 
    description: Allows a player to use the kitupdate command.
    default: op
  sw.vip1:
    description: Gives the player a experience multiplier.
    default: op
  sw.vip2:
    description: Gives the player a experience multiplier.
    default: op
  sw.vip3:
    description: Gives the player a experience multiplier.
    default: op
  sw.vip4:
    description: Gives the player a experience multiplier.
    default: op
  sw.vip5:
    description: Gives the player a experience multiplier.
    default: op