debugMode: false
spawn: null
bungeeMode: false
bungeeLobby: lobby
tauntCooldown: 10
enablePressurePlateJoin: true
teleportToSpawnOnJoin: false
teleportToSpawnOnWorldEnter: true
resourcepack: https://www.dropbox.com/s/8scs6c911y3mqbg/taunts-resource-pack.zip?dl=1
promptForResourcePackOnJoin: false
lobbyBoardEnabled: false
displayPlayerLevelOnXpBar: true
enabledLobbyGuard: false
economyEnabled: false
game:
  ecoForWin: 5
  ecoForKill: 1
  xpForWin: 5
  winCommands: 
  xpForKill: 1
  killCommands:
  vip1Multiplier: 2
  vip2Multiplier: 3
  vip3Multiplier: 4
  vip4Multiplier: 5
  vip5Multiplier: 10
  timeAfterMatch: 15
  gameTimer: 900
  waitTimer: 10
  kitVotingEnabled: false
  spectateEnabled: true
  spectateDistance: 75
  allowFallDamage: false
  maxMapSize: 400
  suddendeath:
    enabled: true
    disableHealthRegen: true
    enableHealthDecay: false
parties:
  enabled: true
  maxPartySize: 4
holograms: 
  enabled: false
kit:
  randPos: 0
  randItem: NETHER_STAR
  noKitPos: 44
  noKitItem: GLASS
titles:
  enabled: true
fireworks:
  enabled: true
  per5Ticks: 1
sounds:
  enabled: true
  countdown: BLOCK_NOTE_BASS
  join: BLOCK_WOODEN_DOOR_OPEN
  leave: BLOCK_WOODEN_DOOR_CLOSE
  openJoinMenu: BLOCK_FENCE_GATE_OPEN
  openSpectateMenu: BLOCK_FENCE_GATE_OPEN
  openOptionsMenu: ENTITY_ZOMBIE_VILLAGER_CURE
  openGlassMenu: BLOCK_GLASS_BREAK
  openWinSoundMenu: ENTITY_FIREWORK_BLAST
  openKillSoundMenu: ENTITY_PIG_DEATH
  openParticleMenu: BLOCK_GRAVEL_STEP
  openProjectileMenu: ENTITY_ARROW_SHOOT
  openTauntMenu: ENTITY_ENDERDRAGON_FLAP
  openKitMenu: ENTITY_PLAYER_ATTACK_SWEEP
  openChestMenu: BLOCK_CHEST_OPEN
  openTimeMenu: ITEM_BOTTLE_FILL_DRAGONBREATH
  openWeatherMenu: WEATHER_RAIN
  openModifierMenu: ENTITY_SPLASH_POTION_BREAK
  confirmSelectionSound: ENTITY_VILLAGER_YES
  errorSound: ENTITY_VILLAGER_NO
signs:
  enabled: true
  blockoffline: COAL_BLOCK
  blockwaiting: EMERALD_BLOCK
  blockplaying: REDSTONE_BLOCK
  blockending: LAPIS_BLOCK
  almostfull: DIAMOND_HELMET
  threefull: GOLD_HELMET
  halffull: IRON_HELMET
  almostempty: LEATHER_HELMET
items:
  kitsEnabled: true
  kitVotePosition: 0
  kitvote: EYE_OF_ENDER
  voteEnabled: true
  votingPosition: 4
  votingItem: COMPASS
  exitGameItem: IRON_DOOR
  exitPosition: 8
  exitMenuItem: BARRIER
  chestVoteEnabled: true
  chestVotePosition: 10
  chestvote: SHIELD
  chestrandom: NETHER_STAR
  chestbasic: STONE_SWORD
  chestnormal: IRON_SWORD
  chestop: DIAMOND_SWORD
  chestscavenger: WOOD_HOE
  nopermission: BARRIER
  timeVoteEnabled: true
  timeVotePosition: 12
  timevote: WATCH
  timerandom: NETHER_STAR
  timedawn: WATCH
  timenoon: WATCH
  timedusk: WATCH
  timemidnight: WATCH
  weatherVoteEnabled: true
  weatherVotePosition: 14
  weathervote: BLAZE_POWDER
  weatherrandom: NETHER_STAR
  weathersunny: PRISMARINE_SHARD
  weatherrain: PRISMARINE_SHARD
  weatherstorm: PRISMARINE_SHARD
  weathersnow: PRISMARINE_SHARD
  modifierVoteEnabled: true
  modifierVotePosition: 16
  modifiervote: DRAGONS_BREATH
  modifierspeed: BOOK
  modifierjump: BOOK
  modifierstrength: BOOK
  modifiernone: BOOK
  modifierrandom: NETHER_STAR
  joinselect: DIAMOND_HELMET
  spectateselect: LEATHER_HELMET
  optionselect: EYE_OF_ENDER
  particleselect: BLAZE_POWDER
  projectileselect: ARROW
  killsoundselect: DIAMOND_SWORD
  killsounditem: NOTE_BLOCK
  winsoundselect: DRAGON_EGG
  glassselect: STAINED_GLASS
  tauntselect: SHIELD
particles:
  enabled: true
  ticksperupdate: 3
enabledMenus:
  join: true
  joinSlot: 0
  spectate: true
  spectateSlot: 4
  options: true
  optionsSlot: 8
  glass: true
  particle: true
  projectile: true
  killsound: true
  winsound: true
  taunts: true
sqldatabase:
  enabled: false
  hostname: localhost
  port: 3306
  database: database
  username: username
  password: password
leaderboards:
  length: 10
  leaderboardUpdateInterval: 300
  signsEnabled: true
  headsEnabled: true  
  eloLeaderboardEnabled: true
  winsLeaderboardEnabled: false
  lossesLeaderboardEnabled: false  
  killsLeaderboardEnabled: false
  deathsLeaderboardEnabled: false
  xpLeaderboardEnabled: false
disable-commands:
  exceptions:
  - msg
  - r
  - sw quit
  enabled: true
disable-commands-spectate:
  exceptions:
  - msg
  - r
  - sw quit
  enabled: true