name: Skywars
main: com.walrusone.skywarsreloaded.SkyWarsReloaded
version: 3.0.9
softdepend: [Vault, PlaceholderAPI, HolographicDisplays]

commands:
   skywars:
      description: This is the main plugin command.
      aliases: [sw]
      usage: /<command> [args]
   swparty:
      description: This is the main party command.
      aliases: [swp]
      usage: /<command> [args]
   swkit:
      description: This is the main party command.
      aliases: [swk]
      usage: /<command> [args]
   swmap:
      description: This is the main party command.
      aliases: [swm]
      usage: /<command> [args]
permissions:
  sw.*:
    description: Gives access to all sw commands
    children:
      sw.admin: true
      sw.party: true
      sw.maps: true
      sw.kits: true
      sw.player: true
      sw.allowcommands: true
  sw.admin:
    description: Gives access to the sw setspawn, list, games, endgame, and reload commands
    default: op
    children:
      sw.maps: true
      sw.kits: true
      sw.player: true
      sw.setspawn: true
      sw.reload: true
      sw.setstat: true
      sw.clearstats: true
      sw.chestadd: true
      sw.start: true
      sw.allowcommands: true
      sw.spectate: true
      sw.updatetop: true
  sw.maps: 
    description: Allows a player to use all map commands.
    default: op
    children:
      sw.map.arenas: true
      sw.map.create: true
      sw.map.creator: true
      sw.map.delete: true
      sw.map.edit: true
      sw.map.list: true
      sw.map.minimum: true
      sw.map.name: true
      sw.map.refresh: true
      sw.map.register: true
      sw.map.save: true
      sw.map.unregister: true
  sw.kits:
    description: Allows a player to use all kit commands.
    default: op
    children:
      sw.kit.create: true
      sw.kit.enable: true
      sw.kit.icon: true
      sw.kit.lockicon: true
      sw.kit.perm: true
      sw.kit.load: true
      sw.kit.list: true
      sw.kit.lore: true
      sw.kit.name: true
      sw.kit.position: true
      sw.kit.update: true
      sw.player: true
  sw.parties:
    description: Allows a player to use all kit commands.
    default: op
    children:
      sw.party.accept: true
      sw.party.decline: true
      sw.party.create: true
      sw.party.disband: true
      sw.party.info: true
      sw.party.invite: true
      sw.party.leave: true
      sw.party.name: true
  sw.player:
    description: Allows a player to using all player commands.
    default: true
    children:
      sw.join: true
      sw.stats: true
      sw.top: true
      sw.quit: true 
  sw.join: 
    description: Allows a player to use sw join command.
    default: true
  sw.spectate: 
    description: Allows a player to use spectate using the spectate menu.
    default: op
  sw.stats: 
    description: Allows a player to view player stats.
    default: true
  sw.top: 
    description: Allows a player to view the leaderboard.
    default: true
  sw.quit: 
    description: Allows a player to use sw quit command.
    default: true
  sw.setspawn:
    description: Allows a player to set a set the lobby spawn.
    default: op
  sw.updatetop:
    description: Allows a player to use the updatetop command.
    default: op
  sw.start:
    description: Allows a player to use the start command.
    default: op
  sw.setstat:
    description: Allows a player to set a players stats.
    default: op
  sw.clearstats:
    description: Allows a player to clear a players stats.
    default: op
  sw.allowcommands:
    description: Allows a player to use commands when spectating or in sw.
    default: op
  sw.reload:
    description: Allows a player to use the reload command.
    default: op
  sw.chestadd:
    description: Allows a player to use the chestadd command.
    default: op
  sw.map.arenas:
    description: Allows a player to use the Arenas GUI.
    default: op  
  sw.map.create:
    description: Allows a player to create a arena.
    default: op
  sw.map.creator:
    description: Allows a player to set the creator for for a arena.
    default: op
  sw.map.edit: 
    description: Allows a player to edit a arena.
    default: op
  sw.map.delete: 
    description: Allows a player to delete a arena.
    default: op
  sw.map.list: 
    description: Allows a player to list the available maps.
    default: op
  sw.map.save:
    description: Allows a player to save a arena.
    default: op
  sw.map.minimum:
    description: Allows a player to set the minimum players for a arena.
    default: op
  sw.map.name:
    description: Allows a player to set the display name for a arena.
    default: op
  sw.map.register:
    description: Allows a player to register a arena.
    default: op
  sw.map.unregister:
    description: Allows a player to unregister a arena.
    default: op
  sw.map.refresh:
    description: Allows a player to reload the maps data file.
    default: op     
  sw.kit.create: 
    description: Allows a player to use the kitcreate command.
    default: op
  sw.kit.enable: 
    description: Allows a player to use the kitenable command.
    default: op
  sw.kit.icon: 
    description: Allows a player to use the kiticon command.
    default: op
  sw.kit.lockicon: 
    description: Allows a player to use the kitlockicon command.
    default: op
  sw.kit.perm: 
    description: Allows a player to use the kitperm command.
    default: op
  sw.kit.load: 
    description: Allows a player to use the kitload command.
    default: op
  sw.kit.list: 
    description: Allows a player to use the kitlist command.
    default: op
  sw.kit.lore: 
    description: Allows a player to use the kitlore command.
    default: op
  sw.kit.name: 
    description: Allows a player to use the kitname command.
    default: op
  sw.kit.position: 
    description: Allows a player to use the kitpos command.
    default: op
  sw.kit.update: 
    description: Allows a player to use the kitupdate command.
    default: op
  sw.party.accept:
    description: Allows a player to accept a party invite.
    default: op
  sw.party.create:
    description: Allows a player to create a party.
    default: op
  sw.party.disband:
    description: Allows a player to disband a party.
    default: op
  sw.party.decline:
    description: Allows a player to decline a party invite.
    default: op
  sw.party.info:
    description: Allows a player to view their party info.
    default: op
  sw.party.invite:
    description: Allows a player to invite others to their party.
    default: op
  sw.party.leave:
    description: Allows a player to leave a party.
    default: op
  sw.vip1:
    description: Gives the player a experience multiplier.
    default: op
  sw.vip2:
    description: Gives the player a experience multiplier.
    default: op
  sw.vip3:
    description: Gives the player a experience multiplier.
    default: op
  sw.vip4:
    description: Gives the player a experience multiplier.
    default: op
  sw.vip5:
    description: Gives the player a experience multiplier.
    default: op